export const GET_PROGRAMS_START = 'GET_PROGRAMS_START';
export const GET_PROGRAMS = 'GET_PROGRAMS';
export const GET_PROGRAMS_SUCCESS = 'GET_PROGRAMS_SUCCESS';
export const GET_PROGRAMS_FAIL = 'GET_PROGRAMS_FAIL';